import Head from "next/head";
import Image from "next/image";
import { FaDiscord, FaWallet } from "react-icons/fa";
import { BsArrowRight } from "react-icons/bs";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Potato NFT</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <nav className="flex justify-between px-20 h-[10vh] items-center border-b border-[#23272a] sticky top-0 z-50 bg-[#2c2f33]">
        <h1 className="text-lg font-semibold">Potato NFT</h1>
        <div className="flex gap-6 items-center">
          <FaWallet className="text-[26px] cursor-pointer" />
          <FaDiscord className="text-[32px] cursor-pointer" />
        </div>
      </nav>
      <div className="grid grid-cols-2 px-20 py-10 gap-10">
        <div className="relative bg-red-400 w-full aspect-square rounded-md overflow-hidden">
          <Image src="/images/77.png" layout="fill" alt="Potato Nft #77" />
        </div>
        <div className="flex items-center justify-center">
          <button className="px-4 py-2 border-2 rounded-md border-[#ccb5ef] flex gap-3 items-center">
            Go to mining page <BsArrowRight />
          </button>
        </div>
      </div>
    </div>
  );
}
